#!/usr/bin/env bash
# MatePad Pro 真机性能验收脚本

set -e
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REPORT="$PROJECT_DIR/reports/matepad-ac-report-$(date +%Y%m%d-%H%M%S).md"

echo "# i-home.life HUAWEI MatePad Pro 真机验收报告" > "$REPORT"
echo "**日期**: $(date '+%Y-%m-%d %H:%M:%S')" >> "$REPORT"
echo "**设备**: HUAWEI MatePad Pro" >> "$REPORT"
echo "**平台**: HarmonyOS (Flutter ohos + Web)" >> "$REPORT"
echo "" >> "$REPORT"

# 1. WebGL 检测
echo "### 1. WebGL 3D 渲染 (AC-8)" >> "$REPORT"
echo "" >> "$REPORT"
echo "在 MatePad Pro 浏览器中打开: $PROJECT_DIR/web/3d-viewer.html" >> "$REPORT"
echo "" >> "$REPORT"
echo "| 指标 | 目标 | 实测 | 状态 |" >> "$REPORT"
echo "|------|------|------|------|" >> "$REPORT"
echo "| 户型加载时间 | < 3s | ___ | ⏳ |" >> "$REPORT"
echo "| FPS (126㎡户型) | ≥ 30 | ___ | ⏳ |" >> "$REPORT"
echo "| FPS (160㎡户型) | ≥ 30 | ___ | ⏳ |" >> "$REPORT"
echo "| 面数 | — | ___ | — |" >> "$REPORT"
echo "| 抗锯齿 | 开启 | ✅ | ✅ |" >> "$REPORT"
echo "| 阴影 | 开启 | ✅ | ✅ |" >> "$REPORT"
echo "" >> "$REPORT"

# 2. 2D CAD 交互
echo "### 2. 2D CAD 绘图 (AC-1/AC-2)" >> "$REPORT"
echo "" >> "$REPORT"
echo "在浏览器中打开: $PROJECT_DIR/web/studio.html" >> "$REPORT"
echo "" >> "$REPORT"
echo "| 测试项 | 结果 | 备注 |" >> "$REPORT"
echo "|--------|------|------|" >> "$REPORT"
echo "| 手指拖拽画矩形 | ___ | ___ |" >> "$REPORT"
echo "| M-Pencil 画矩形 | ___ | ___ |" >> "$REPORT"
echo "| 压感变化 (线宽) | ___ | ___ |" >> "$REPORT"
echo "| 双指缩放 | ___ | ___ |" >> "$REPORT"
echo "| 正交锁定 | ___ | ___ |" >> "$REPORT"
echo "| 对象捕捉 | ___ | ___ |" >> "$REPORT"
echo "| 7 种工具切换 | ___ | ___ |" >> "$REPORT"
echo "" >> "$REPORT"

# 3. Flutter App
echo "### 3. Flutter Native App (AC-8)" >> "$REPORT"
echo "" >> "$REPORT"
echo "HAP 安装: $PROJECT_DIR/flutter_app/build/outputs/hap/" >> "$REPORT"
echo "" >> "$REPORT"
echo "| 指标 | 目标 | 实测 | 状态 |" >> "$REPORT"
echo "|------|------|------|------|" >> "$REPORT"
echo "| CAD 引擎 FPS | ≥ 30 | ___ | ⏳ |" >> "$REPORT"
echo "| 启动时间 | < 2s | ___ | ⏳ |" >> "$REPORT"
echo "| M-Pencil 压感响应 | < 16ms | ___ | ⏳ |" >> "$REPORT"
echo "| 双击切换工具 | 可用 | ___ | ⏳ |" >> "$REPORT"
echo "| 崩溃率 (30min) | 0 | ___ | ⏳ |" >> "$REPORT"
echo "" >> "$REPORT"

# 4. 综合结论
echo "### 4. 综合结论" >> "$REPORT"
echo "" >> "$REPORT"
echo "| AC | 验收项 | MatePad 实测 | 状态 |" >> "$REPORT"
echo "|----|--------|-------------|------|" >> "$REPORT"
echo "| AC-1 | 2D 绘图交互 | ___ | ⏳ |" >> "$REPORT"
echo "| AC-2 | 对象捕捉 | ___ | ⏳ |" >> "$REPORT"
echo "| AC-3 | 3D 模型生成 | ___ | ⏳ |" >> "$REPORT"
echo "| AC-4 | 平立剖生成 | ___ | ⏳ |" >> "$REPORT"
echo "| AC-5 | DXF 导出 | ___ | ⏳ |" >> "$REPORT"
echo "| AC-6 | Agent 响应 | ___ | ⏳ |" >> "$REPORT"
echo "| AC-7 | Agent 完成率 | ___ | ⏳ |" >> "$REPORT"
echo "| AC-8 | 性能 ≥ 30fps | ___ | ⏳ |" >> "$REPORT"
echo "| AC-9 | 崩溃率 < 0.1% | ___ | ⏳ |" >> "$REPORT"
echo "" >> "$REPORT"
echo "---" >> "$REPORT"
echo "*报告: 请在 MatePad Pro 上执行对应测试后填写 `___` 字段*" >> "$REPORT"

echo "✅ 报告模板已生成: $REPORT"
echo ""
echo "📋 接下来请执行:"
echo ""
echo "  1. Web 工具验证:"
echo "     ● 启动后端: bash scripts/deploy.sh start"
echo "     ● MatePad 浏览器打开: file://$PROJECT_DIR/web/studio.html"
echo "     ● 测试 M-Pencil 绘图 + AI 布局 + 3D 预览"
echo ""
echo "  2. Flutter App 验证:"
echo "     ● 编译: bash scripts/deploy-ohos.sh"
echo "     ● 安装: hdc install flutter_app/build/outputs/hap/*.hap"
echo "     ● 打开 App → 设计台 Tab → 用 M-Pencil 绘图"
echo ""
echo "  3. 填写报告: open $REPORT"
